### ISSUE TITLE
instant-markdown-d doesn't parse Header any more

### ISSUE THREAD

**Issue by kevin4fly** [suan/instant-markdown-d#27]
In the other day, the `instant-markdown-d` works fine. However, it doesn't parse header any more after  run `npm -g update instant-markdown-d` to update to the latest version.

Type `echo "###hello" | instant-markdown-d` into terminal, the web browser pops up and shows "###hello" exactly instead of parsing it to header 3rd-sized.

**Comment by kevin4fly** [comment]
Add the screenshot:

![markdown](https://cloud.githubusercontent.com/assets/3070033/8509923/b75c77fa-22f7-11e5-8405-6c83bd722833.jpg)

**Comment by ashwinvis** [comment]
You missed a space `echo "### hello" | instant-markdown-d`
