### ISSUE TITLE
[Feature] include support for [X] checkboxes

### ISSUE THREAD

**Issue by andykais** [suan/instant-markdown-d#39]
I would love to see support for checkboxes like this
- [x] checked
- [ ] unchecked

whose syntax is `- [x]`. This is a [Github Flavor Markdown feature](https://guides.github.com/features/mastering-markdown/). Its support should not affect any other existing syntax, so it would only be an added feature that users may or may not choose to use

**Comment by ashwinvis** [comment]
Done in #60

**Comment by andykais** [comment]
Woo! Thank you!
