### ISSUE TITLE
npm ERR not a package instant-markdown-d on Windows 7 system

### ISSUE THREAD

**Issue by dinmshi** [suan/instant-markdown-d#42]
npm ERR! not a package C:\Users\xiaozhu\markdown-d\instant-markdown-d\inst
rkdown-d
npm ERR! addLocal Could not install C:\Users\xiaozhu\markdown-d\instant-ma
-d\instant-markdown-d
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\no
node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "instant-markdown-d"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\xiaozhu\AppData\Local\Temp\npm-6112-663754d1\unpack
e2b\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\xiaozhu\
a\Local\Temp\npm-6112-663754d1\unpack-960c4e2b\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\xiaozhu\
a\Local\Temp\npm-6112-663754d1\unpack-960c4e2b\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xiaozhu\markdown-d\instant-markdown-d\npm-debug.log

**Comment by ashwinvis** [comment]
Please install version 0.1.1
