### ISSUE TITLE
Add ability to configure browser autostart.

### ISSUE THREAD

**Issue by systemmonkey42** [suan/instant-markdown-d#48]
Can we disable the browser auto-launching?  I edit via SSH and use a local browser to connect to the global port if possible, or the local port via SSH tunnel, but the latest version seems to fail if it can't launch a browser.

I've seen pull requests which let you configure the browser to use, but they don't support a 'none' browser, or browser disable functionality.

**Comment by Migacz85** [comment]
Yeees please, option to configure which browser to use would be fantastic.

**Comment by ashwinvis** [comment]
If you run `instant-markdown-d --debug` added in #60 it will not launch browser.
